create extension if not exists pg_trgm;

create table patient (
    id                    uuid primary key,
    clinic_id             uuid         not null references clinic (id),
    document_type         varchar(2)   not null,
    document_number       varchar(20)  not null,
    first_name            varchar(60)  not null,
    middle_name           varchar(60),
    first_last_name       varchar(60)  not null,
    second_last_name      varchar(60),
    birth_date            date         not null,
    sex                   varchar(1)   not null check (sex in ('H', 'M', 'I')),
    phone                 varchar(30),
    email                 varchar(160),
    address               varchar(200),
    municipality          varchar(80),
    residence_zone        varchar(1) check (residence_zone in ('U', 'R')),
    regime                varchar(20)  not null,
    insurer               varchar(120),
    occupation            varchar(80),
    guardian_name         varchar(150),
    guardian_phone        varchar(30),
    guardian_relationship varchar(40),
    notes                 varchar(1000),
    active                boolean      not null default true,
    -- Nombres + documento en minúsculas y sin tildes, para buscar "jose" y encontrar "José".
    search_key            varchar(400) not null,
    created_at            timestamptz  not null default now(),
    updated_at            timestamptz  not null default now(),
    constraint uq_patient_document unique (clinic_id, document_type, document_number)
);
create index ix_patient_search on patient using gin (search_key gin_trgm_ops);
create index ix_patient_clinic_name on patient (clinic_id, first_last_name, first_name);

alter table patient enable row level security;
create policy tenant_isolation on patient
    using (app_rls_bypass() or clinic_id = app_current_clinic())
    with check (app_rls_bypass() or clinic_id = app_current_clinic());

-- ---------- Auditoría (Hibernate Envers) ----------
-- Una revisión por transacción: quién, cuándo y en qué clínica.
create table audit_revision (
    id            bigint generated by default as identity primary key,
    rev_timestamp bigint not null,
    clinic_id     uuid,
    user_id       uuid
);

alter table audit_revision enable row level security;
create policy tenant_isolation on audit_revision
    using (app_rls_bypass() or clinic_id = app_current_clinic())
    with check (app_rls_bypass() or clinic_id = app_current_clinic());

-- Copia de cada versión del paciente. revtype: 0 = creado, 1 = modificado, 2 = eliminado.
create table patient_aud (
    id                    uuid     not null,
    rev                   bigint   not null references audit_revision (id),
    revtype               smallint,
    clinic_id             uuid,
    document_type         varchar(2),
    document_number       varchar(20),
    first_name            varchar(60),
    middle_name           varchar(60),
    first_last_name       varchar(60),
    second_last_name      varchar(60),
    birth_date            date,
    sex                   varchar(1),
    phone                 varchar(30),
    email                 varchar(160),
    address               varchar(200),
    municipality          varchar(80),
    residence_zone        varchar(1),
    regime                varchar(20),
    insurer               varchar(120),
    occupation            varchar(80),
    guardian_name         varchar(150),
    guardian_phone        varchar(30),
    guardian_relationship varchar(40),
    notes                 varchar(1000),
    active                boolean,
    primary key (id, rev)
);

alter table patient_aud enable row level security;
create policy tenant_isolation on patient_aud
    using (app_rls_bypass() or clinic_id = app_current_clinic())
    with check (app_rls_bypass() or clinic_id = app_current_clinic());

-- La auditoría es de solo-agregar: la app no puede editar ni borrar el historial.
revoke update, delete on audit_revision, patient_aud from ${app_role};
